var abilityLibrary = {
    'punch': {
        type: 0,
        name: "Punch",
        iconName: "punch",
        baseDamage: 1,
        damageRatios: [.8,0,0,0.2],
        time: 3000,
        cooldownTime: 0,
        range: 5,

    },
    'smash': {
        type: 0,
        name: "Smash",
        iconName: "smash",
        baseDamage: 5,
        damageRatios: [2.5,1,0,0],
        time: 7000,
        cooldownTime: 10000,
        range: 5,

    },
    'crowbar': {
        type: 0,
        name: "Crowbar",
        iconName: "crowbar",
        baseDamage: 1,
        damageRatios: [3, 0, 0, 0],
        damageRange: [1, 1.1],
        time: 4000,
        cooldownTime: 20000,
        range: 5,
    },
    'shank': {
        type: 0,
        name: "Shank",
        iconName: "throwingKnife",
        baseDamage: 1,
        damageRatios: [2, 0, 0, 1],
        damageRange: [1, 1.1],
        time: 4000,
        cooldownTime: 5000,
        range: 5,
    },
    'vomit': {
        type: 0,
        name: "Vomit",
        iconName: "vomit",
        baseDamage: 1,
        damageRatios: [0, 3, 0, 0],
        damageRange: [0.9, 1.1],
        time: 3000,
        cooldownTime: 7000,
        range: 10,
    },
    'mutantSlash': {
        type: 0,
        name: "Slash",
        iconName: "mutantSlash",
        baseDamage: 1,
        damageRatios: [1.5, 1, 0, 0],
        damageRange: [1, 1.5],
        time: 4000,
        cooldownTime: 12000,
        range: 15,
    },
    'walk': {
        type: 1,
        name: "Move",
        iconName: "move",
        baseDamage: 0,
        time: 1000,
        cooldownTime: 0,
        range: 5,
    }
};

var enemyData = {};

enemyData.criminal = {
    id:"criminal",
    name: "Purse thief",
    maxHealth: 2.5,
    attributes: [.5,.5,0,1],
    healthRegen: 0,
    expReward: 1,
    moneyReward: 0.03,
    reputationReward: 1,
    spriteFile: "crim.png",
    portraitFile: "crimPortrait.png",
    moves: ['punch','walk'],
};
enemyData.thug = {
    id:"thug",
    name: "Thug",
    maxHealth: 15,
    attributes: [5,3,1,2],
    healthRegen: 0,
    expReward: 5,
    moneyReward: 0.05,
    reputationReward: 1,
    spriteFile: "thug.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch','walk','crowbar'],
};
enemyData.prisoner = {
    id:"prisoner",
    name: "Prisoner",
    maxHealth: 40,
    attributes: [10,10,1,10],
    healthRegen: 0,
    expReward: 15,
    moneyReward: 0.1,
    reputationReward: 1,
    spriteFile: "prisoner.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch','walk','shank'],
};
enemyData.prisoner9 = {
    id:"prisoner9",
    name: "Prisoner 9",
    maxHealth: 120,
    attributes: [50,50,1,5],
    healthRegen: 0.005,
    expReward: 25,
    moneyReward: 0.5,
    reputationReward: 1,
    spriteFile: "prisoner9.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['punch','smash','walk'],
};
enemyData.infectedPrisoner = {
    id:"infectedPrisoner",
    name: "Strange Prisoner",
    maxHealth: 100,
    attributes: [40,50,1,30],
    healthRegen: 0.01,
    expReward: 50,
    moneyReward: 2,
    reputationReward: 1,
    spriteFile: "infectedPrisoner.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch','walk','vomit'],
};
enemyData.experiment999 = {
    id:"experiment999",
    name: "Experiment #999",
    maxHealth: 400,
    attributes: [200,200,10,100],
    healthRegen: 0.01,
    expReward: 300,
    moneyReward: 5,
    reputationReward: 1,
    spriteFile: "experiment999.png",
    portraitFile: "thugPortrait.png",
    moves: ['walk','punch','mutantSlash','vomit'],
};
enemyData.experiment9999 = {
    id:"experiment9999",
    name: "Expriment #9999",
    maxHealth: 5000,
    attributes: [5000,2000,100,500],
    healthRegen: 0.005,
    expReward: 2500,
    moneyReward: 200,
    reputationReward: 1,
    spriteFile: "experiment999.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['walk','punch','smash','mutantSlash','vomit'],
};

