var summons = {
    'shadowClone': {
        id: "shadowClone", name: "Shadow Clone",
        attributes: [1,1,1,1],
        combatProperties: new CombatProperties(),
        spriteFile: "shadowClone.png",
        moves: ['katana','shuriken', 'shadowWalk'],
        engagementRange: 5,
        duration: 5000,
    },
    'allyTentacle': {
        id: "allyTentacle", name: "Summoned Tentacle",
        attributes: [1,1,1,1],
        combatProperties: new CombatProperties(),
        spriteFile: "allyTentacle.png",
        moves: ['tendrilWhip','slowWalk'],
        engagementRange: 10,
        duration: 10000,
    },
    'allyWolf': {
        id: "allyWolf", name: "Wolf",
        attributes: [1,1,1,1],
        combatProperties: new CombatProperties(),
        spriteFile: "allyWolf.png",
        moves: ['clawStrike','walk'],
        modifiers:{actionSpeed:3},
        engagementRange: 5,
        duration: 5000,
    },
    'allyMitosis': {
        id: "allyMitosis", name: "Mitosis Clone",
        attributes: [1,1,1,1],
        combatProperties: new CombatProperties(),
        spriteFile: "mutantSprite1.png",
        moves: ['bulkFist','walk'],
        modifiers:{},
        engagementRange: 5,
        duration: 30000,
    },
    'allyFrog': {
        id: "allyFrog", name: "Great Frog",
        attributes: [1,1,1,1],
        combatProperties: new CombatProperties(),
        spriteFile: "giantFrog.png",
        moves: ['tongueWhip','acidBlob','walk'],
        modifiers:{},
        engagementRange: 30,
        duration: 15000,
    },
    'allySpectre': {
        id: "allySpectre", name: "Spectre",
        attributes: [1,1,1,1],
        combatProperties: new CombatProperties(),
        spriteFile: "placeholder.png",
        moves: ['haunting','spiritBurst','walk'],
        modifiers:{},
        engagementRange: 10,
        duration: 30000,
    }
}