playerMoves = {
    'punch': {
        type: 0,
        category: 'melee',
        name: "Punch",
        description: "A simple punch, everyone knows how to do it.",
        iconName: "punch",
        damage: 1,
        damageRatios: [.8, 0, 0, 0.2],
        damageRange: [0.9, 1.1],
        time: 3000,
        cooldownTime: 0,
        range: [5, 5],
    },
    'kick': {
        class: 'human',
        sub: 0,
        position: { row: 1, column: 1 },
        type: 0,
        category: 'melee',
        name: "Roundhouse Kick",
        description: "Leverage your lower body strength to knock those criminals on their asses",
        iconName: "kick",
        damage: 2,
        damageRatios: [1.2, 0, 0, 0.4],
        damageRange: [1, 1.2],
        effects: {
            'aoe': 5,
        },
        time: 4000,
        cooldownTime: 5000,
        range: [5, 5],
        cost: 1,
    },
    'jab': {
        class: 'human',
        type: 0,
        sub: 0,
        position: { row: 2, column: 1 },
        category: 'melee',
        name: "Throat Jab",
        description: "A fast jab to the throat momentarily stuns your foe.",
        iconName: "jab",
        damage: 1,
        damageRatios: [.3, 0, 0, .9],
        damageRange: [.95, 1.05],
        effects: {
            'stun': 1,
        },
        time: 1000,
        cooldownTime: 7000,
        range: [5, 5],
        cost: 1,
    },
    'haymaker': {
        class: 'human',
        type: 0,
        sub: 0,
        position: { row: 3, column: 1 },
        category: 'melee',
        name: "Haymaker",
        description: "Prepare to deliver a massive blow to your foe. Slow.",
        iconName: "smash",
        damage: 1,
        damageRatios: [2, 1, 0, 0],
        damageRange: [1.1, 1.4],
        time: 7000,
        cooldownTime: 10000,
        range: [5, 5],
        cost: 1,
    },
    'crowbar': {
        class: 'human',
        type: 0,
        sub: 0,
        position: { row: 4, column: 1 },
        category: 'melee',
        name: "Crowbar",
        description: "This does not seem fair?",
        iconName: "crowbar",
        damage: 1,
        damageRatios: [2.5, 0, 0, 0],
        damageRange: [1, 2],
        time: 3000,
        cooldownTime: 15000,
        range: [6, 6],
        cost: 1,
    },
    'throwingKnife': {
        class: 'human',
        sub: 0,
        position: { row: 5, column: 1 },
        class: 'human',
        type: 0,
        category: 'ranged',
        name: "Throwing Knife",
        description: "It's funnier in the circus",
        iconName: "throwingKnife",
        damage: 1,
        damageRatios: [0, 0, .4, .8],
        damageRange: [0.8, 1],
        time: 2000,
        cooldownTime: 4000,
        range: [0, 60],
        cost: 1,
    },
    'firecrackers': {
        class: 'human',
        type: 0,
        sub: 0,
        position: { row: 6, column: 1 },
        category: 'ranged',
        name: "Firecackers",
        description: "You're more likely to blow off your own fingers than theirs.",
        iconName: "firecrackers",
        damage: 1,
        damageRatios: [0, 0, 1.8, .6],
        damageRange: [1, 2],
        effects: {
            'aoe': 5,
        },
        time: 3000,
        cooldownTime: 9000,
        range: [0, 30],
        cost: 1,
    },
    //Esper
    'spiritFist': {
        class: 'esper',
        type: 0,
        sub: 2,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Spirit Fist",
        description: "Empower your fist with psionic energy for an enhanced strike.",
        iconName: "spiritFist",
        damage: 1,
        damageRatios: [.2, 0, 1, .2],
        damageRange: [0.9, 1.1],
        time: 3000,
        cooldownTime: 0,
        range: [6, 6],
        cost: 1,
    },
    'telekineticProjectile': {
        class: 'esper',
        type: 0,
        sub: 0,
        position: { row: 1, column: 1 },
        category: 'ranged',
        name: "Telekinetic Projectile",
        description: "Use your psionic powers to thrust nearby matter towards your enemy.",
        iconName: "telekineticProjectile",
        damage: 1,
        damageRatios: [0, 0, 1.8, 0],
        damageRange: [0.8, 1.1],
        time: 3000,
        cooldownTime: 5000,
        range: [10, 60],
        cost: 5,
    },
    'psionicPulse': {
        class: 'esper',
        type: 0,
        sub: 0,
        position: { row: 3, column: 1 },
        category: 'melee',
        name: "Psionic Pulse",
        description: "Emit a short-range pulse that damages and knocks back nearby enemies.",
        iconName: "psionicPulse",
        damage: 1,
        damageRatios: [0, .5, 1.5, 0],
        damageRange: [1, 1.2],
        effects: {
            'knockback': 10,
            'aoe': 20,
        },
        time: 3000,
        cooldownTime: 10000,
        range: [20, 20],
        cost: 5,
    },
    'psionicBarrier': {
        class: 'esper',
        type: 2,
        sub: 0,
        position: { row: 2, column: 5 },
        category: 'ranged',
        name: "Psionic Barrier",
        description: "Form a temporary barrier to block attacks.",
        iconName: "psionicBarrier",
        damage: 0,
        damageRatios: [0, 0, 0.5, 0],
        damageRange: [1, 1],
        effects: {
            'shield': 0,
        },
        time: 1000,
        cooldownTime: 20000,
        range: [0, 0],
        cost: 5,
    },
    'repulsionWave': {
        class: 'esper',
        type: 0,
        sub: 1,
        position: { row: 3, column: 1 },
        category: 'melee',
        name: "Repulsion Wave",
        description: "Emit reality-altering waves to give you some space",
        iconName: "repulsionWave",
        damage: 0,
        damageRatios: [0, .1, .2, 0],
        damageRange: [1, 1],
        effects: {
            'knockback': 15,
            'aoe': 30,
            'repeat': 0.75,
        },
        time: 500,
        cooldownTime: 30000,
        range: [30, 30],
        cost: 5,
    },
    'aflamingpunch': {
        class: 'esper',
        type: 0,
        sub: 1,
        position: { row: 3, column: 5 },
        category: 'melee',
        name: "Augment: Flaming Punch",
        description: "Increase the kinetic energy around your fist to produce flames that erupt on impact",
        iconName: "aflamingpunch",
        damage: 0,
        damageRatios: [1, 0, 1, 1],
        damageRange: [1, 1],
        effects: {
            'aoe': 5,
        },
        time: 2500,
        cooldownTime: 3000,
        range: [5, 5],
        cost: 5,
    },
    'afreezingpunch': {
        class: 'esper',
        type: 0,
        sub: 1,
        position: { row: 5, column: 5 },
        category: 'melee',
        name: "Augment: Freezing Punch",
        description: "Sap the kinetic energy around your fist to produce ice that erupts on impact",
        iconName: "afreezingpunch",
        damage: 0,
        damageRatios: [1, 0, 1, 1],
        damageRange: [1, 1],
        effects: {
            'stun': 0.5,
        },
        time: 2500,
        cooldownTime: 3000,
        range: [5, 5],
        cost: 5,
    },
    'conjureLightning': {
        class: 'esper',
        type: 0,
        sub: 1,
        position: { row: 5, column: 1 },
        category: 'ranged',
        name: "Conjure: Lightning",
        description: "Alter the charge in the air to conjure a bolt of lightning",
        iconName: "conjureLightning",
        damage: 0,
        damageRatios: [0, 0, 3, 2],
        damageRange: [1, 3],
        effects: {
            'criticalChance': 25,
        },
        time: 3000,
        cooldownTime: 20000,
        range: [0, 100],
        cost: 5,
    },
    //Mutant
    'bulkFist': {
        class: 'mutant',
        type: 0,
        sub: 0,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Bulk Fist",
        description: "Enlarge your fist to deliver a solid blow.",
        iconName: "bulkFist",
        damage: 1,
        damageRatios: [.7, .8, 0, 0],
        damageRange: [1, 1.1],
        time: 4000,
        cooldownTime: 0,
        range: [5, 5],
        cost: 1,
    },
    'tentaclePull': {
        class: 'mutant',
        type: 0,
        sub: 1,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Tendril Pull",
        description: "Morph your arm out into a tentacle and pull your foe closer",
        iconName: "tentaclePull",
        damage: 1,
        damageRatios: [.1, .3, 0, 0],
        damageRange: [1, 1],
        effects: {
            'pull': 30
        },
        time: 1500,
        cooldownTime: 5000,
        range: [60, 60],
        cost: 5,
    },
    'corrosiveBurst': {
        class: 'mutant',
        type: 0,
        sub: 0,
        position: { row: 4, column: 1 },
        category: 'melee',
        name: "Corrosive Burst",
        description: "Your skin explodes, covering nearby foes in acid.",
        iconName: "corrosiveBurst",
        damage: 1,
        damageRatios: [0, 1.4, 0.8, 0],
        damageRange: [0.8, 1.2],
        effects: {
            'aoe': 10
        },
        time: 4000,
        cooldownTime: 10000,
        range: [10, 10],
        cost: 5,
    },
    'engulf': {
        class: 'mutant',
        type: 0,
        sub: 0,
        position: { row: 3, column: 5 },
        category: 'melee',
        name: "Engulf",
        description: "Try to completely subdue your target by englufing them. Deals extra damage to damaged enemies.",
        iconName: "engulf",
        damage: 1,
        damageRatios: [0, 5, 0, 0],
        damageRange: [0.9, 1],
        effects: {
            'takedown': 1,
        },
        time: 6000,
        cooldownTime: 30000,
        range: [5, 5],
        cost: 5,
    },
    'clawStrike': {
        class: 'mutant',
        type: 0,
        sub: 2,
        position: { row: 1, column: 5 },
        category: 'melee',
        name: "Clawstrike",
        description: "Rapidly grow claws out of your fist for a feral strike.",
        iconName: "clawStrike",
        damage: 0,
        damageRatios: [0, .2, 0, 0.3],
        damageRange: [.8, 1.2],
        time: 1500,
        cooldownTime: 0,
        range: [5, 5],
        cost: 1,
    },
    'monkeySmash': {
        class: 'mutant',
        type: 0,
        sub: 2,
        position: { row: 5, column: 5 },
        category: 'melee',
        name: "Monkey Smash",
        description: "With the power of monke strength, smash your foe over the head, stunning him.",
        iconName: "monkeySmash",
        damage: 0,
        damageRatios: [3, 1, 0, 0],
        damageRange: [0.8, 1],
        effects: {
            'stun': 3,
        },
        time: 6000,
        cooldownTime: 12000,
        range: [5, 5],
        cost: 5,
    },
    'tigerPounce': {
        class: 'mutant',
        type: 0,
        sub: 2,
        position: { row: 3, column: 5 },
        category: 'melee',
        name: "Tiger Pounce",
        description: "Leap to you enemy, slashing with your claws.",
        iconName: "placeholder",
        damage: 0,
        damageRatios: [3, 1, 0, 0],
        damageRange: [0.8, 1],
        effects: {
            'rush': 0,
        },
        time: 2000,
        cooldownTime: 12000,
        range: [50,50],
        cost: 5,
    },
    'distortedVisage': {
        class: 'mutant',
        type: 0,
        sub: 1,
        position: { row: 3, column: 5 },
        category: 'melee',
        name: "Distorted Visage",
        description: "Twist your face into an abominable sight, disgusting nearby enemies to the point of fear.",
        iconName: "placeholder",
        damage: 0,
        damageRatios: [0, 1, 1, 0],
        damageRange: [0.8, 1],
        effects: {
            'stun': 1,
            'aoe': 10,
        },
        time: 2000,
        cooldownTime: 12000,
        range: [10, 10],
        cost: 5,
    },
    //Superhuman
    'simplePunch': {
        class: 'superhuman',
        type: 0,
        sub: 0,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Simple Punch",
        description: "I fear not the man who has practiced 10,000 punches once, but I fear the man who has practiced one punch 10,000 times.",
        iconName: "punch",
        damage: 1,
        damageRatios: [1.5, 0, 0, 0],
        damageRange: [0.8, 1.2],
        time: 3000,
        cooldownTime: 0,
        range: [5, 5],
        cost: 1,
    },
    'multipleSimplePunches': {
        class: 'superhuman',
        type: 0,
        sub: 0,
        position: { row: 3, column: 1 },
        category: 'melee',
        name: "Multiple Simple Punches",
        description: "I fear not the man who has practiced 10,000 punches once, but I fear the man who has practiced one 10,000 punches, 10,000 times.",
        iconName: "multipleSimplePunches",
        damage: 1,
        damageRatios: [.3, 0, 0, .3],
        damageRange: [0.8, 1.2],
        effects: {
            'repeat': 0.5,
        },
        time: 500,
        cooldownTime: 2000,
        range: [5, 5],
        cost: 5,
    },
    'solarPlexusStrike': {
        class: 'superhuman',
        type: 0,
        sub: 0,
        position: { row: 3, column: 5 },
        category: 'melee',
        name: "Solar Plexus Strike",
        description: "Knock the wind out of your foe with an unexpected blow",
        iconName: "solarPlexusStrike",
        damage: 1,
        damageRatios: [2.5, 0, 0, 1.5],
        damageRange: [0.8, 1.2],
        effects: {
            'stun': 4,
        },
        time: 3000,
        cooldownTime: 20000,
        range: [5, 5],
        cost: 5,
    },
    'titanicSwing': {
        class: 'superhuman',
        type: 0,
        sub: 1,
        position: { row: 3, column: 1 },
        category: 'melee',
        name: "Titanic Swing",
        description: "Wind up to deliver the greatest blow your body allows",
        iconName: "smash",
        damage: 1,
        damageRatios: [5, 2, 0, 0],
        damageRange: [1, 1.5],
        effects: {
            'knockback': 20,
        },
        time: 5000,
        cooldownTime: 20000,
        range: [10, 10],
        cost: 5,
    },
    'airCannon': {
        class: 'superhuman',
        type: 0,
        sub: 1,
        position: { row: 1, column: 1 },
        category: 'ranged',
        name: "Air Cannon",
        description: "You punch the air so hard that a shockwave is launched towards the enemy",
        iconName: "airCannon",
        damage: 1,
        damageRatios: [1, 0, 0, 0],
        damageRange: [1, 1],
        effects: {
            'aoe': 5,
            'knockback': 5
        },
        time: 3000,
        cooldownTime: 5000,
        range: [5, 50],
        cost: 5,
    },
    'groundStomp': {
        class: 'superhuman',
        type: 0,
        sub: 1,
        position: { row: 2, column: 5 },
        category: 'melee',
        name: "Ground Stomp",
        description: "Slam your foot down causing a tremor around you that destabilizes nearby foes",
        iconName: "placeholder",
        damage: 0,
        damageRatios: [1, 1, 0, 0],
        damageRange: [1, 1],
        effects: {
            'stun': 2,
            'aoe': 10,
        },
        time: 3000,
        cooldownTime: 12000,
        range: [5, 5],
        cost: 5,
    },
    'secondWind': {
        class: 'superhuman',
        type: 2,
        sub: 2,
        position: { row: 3, column: 5 },
        category: 'ranged',
        name: "Second Wind",
        description: "Take a few breaths and let your supernatural constitution catch up.",
        iconName: "secondWind",
        damage: 0,
        damageRatios: [0.06, .6, 0, 0],
        damageRange: [1, 1],
        effects: {
            'heal': 0,
            'hope': 1,
        },
        time: 1000,
        cooldownTime: 14000,
        range: [0, 0],
        cost: 5,
    },
    'kiBlast': {
        class: 'superhuman',
        type: 0,
        sub: 2,
        position: { row: 1, column: 1 },
        category: 'ranged',
        name: "Ki Blast",
        description: "Form and discharge a blast of ki from your hand",
        iconName: "kiBlast",
        damage: 0,
        damageRatios: [1, 0, 1, 0],
        damageRange: [1, 1.1],
        effects: {},
        time: 3000,
        cooldownTime: 5000,
        range: [0, 20],
        cost: 5,
    },
    'energyKick': {
        class: 'superhuman',
        sub: 2,
        position: { row: 3, column: 1 },
        type: 0,
        category: 'melee',
        name: "Energy Kick",
        description: "Leverage your lower body strength and ki manipulation to kick a wave of energy",
        iconName: "energyKick",
        damage: 0,
        damageRatios: [1.2, 0, 1, 0.4],
        damageRange: [1, 1.2],
        effects: {
            'aoe': 10,
        },
        time: 3000,
        cooldownTime: 5000,
        range: [5, 5],
        cost: 1,
    },
    //NINJA
    'katana': {
        class: 'ninja',
        type: 0,
        sub: 0,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Katana",
        description: "A ninja's weapon (?).",
        iconName: "katana",
        damage: 0,
        damageRatios: [.4, 0, 0, .6],
        damageRange: [0.9, 1.1],
        time: 2500,
        cooldownTime: 0,
        range: [5, 5],
        cost: 1,
    },
    'deflect': {
        class: 'ninja',
        type: 2,
        sub: 0,
        position: { row: 2, column: 5 },
        category: 'melee',
        name: "Deflect",
        description: "Be ready to lessen the blow of the next attack.",
        iconName: "deflect",
        damage: 0,
        damageRatios: [0.1, 0, 0, 0.05],
        damageRange: [1, 1],
        effects: {
            'shield': 0,
            'closeCombat': 0,
        },
        cost: 5,
        time: 500,
        cooldownTime: 5000,
        range: [0, 0],
        cost: 5,
    },
    'shadowStrike': {
        class: 'ninja',
        type: 0,
        sub: 2,
        position: { row: 2, column: 1 },
        category: 'melee',
        name: "Shadow Strike",
        description: "Instantly appear near you enemy and strike them before reappearing at your position.",
        iconName: "jab",
        damage: 1,
        damageRatios: [0, 0, 1, 2],
        damageRange: [1, 1.2],
        time: 2000,
        cooldownTime: 10000,
        range: [30, 30],
        cost: 5,
    },
    'shuriken': {
        class: 'ninja',
        type: 0,
        sub: 1,
        position: { row: 1, column: 1 },
        category: 'ranged',
        name: "Shuriken",
        description: "Launch a number of shuriken at your foes.",
        iconName: "shuriken",
        damage: 1,
        damageRatios: [0, 0, 0.05, .15],
        damageRange: [1, 1.1],
        effects: {
            'aoe': 5,
            'repeat': 0.75,
        },
        time: 500,
        cooldownTime: 2000,
        range: [10, 60],
        cost: 5,
    },
    'ninjaFireBreath': {
        class: 'ninja',
        type: 0,
        sub: 1,
        position: { row: 2, column: 1 },
        category: 'melee',
        name: "Technique: Fire Breath",
        description: "Perform the ninja signs allowing you to breath a cone of fire at your foes.",
        iconName: "ninjaFireBreath",
        damage: 0,
        damageRatios: [0, 0, 3, 1],
        damageRange: [1, 1.1],
        effects: {
            'aoe': 20,
        },
        time: 4000,
        cooldownTime: 15000,
        range: [20, 20],
        cost: 5,
    },
    'healingSlave': {
        class: 'ninja',
        type: 2,
        sub: 1,
        position: { row: 2, column: 5 },
        category: 'melee',
        name: "Herbal Salve",
        description: "Apply a salve to your wounds to speed up recovery.",
        iconName: "placeholder",
        damage: 0,
        damageRatios: [0, 0, 0, 0],
        damageRange: [1, 1],
        effects: {
            'heal': 0.1,
        },
        time: 2000,
        cooldownTime: 20000,
        range: [0, 0],
        cost: 5,
    },
    'flashStep': {
        class: 'ninja',
        type: 1,
        sub: 1,
        position: { row: 3, column: 1 },
        category: 'movement',
        name: "Flash Step",
        description: "Use the secret techniques to rapidly travel a greater distance.",
        iconName: "move",
        damage: 0,
        time: 500,
        cooldownTime: 5000,
        range: [20, 0],
        cost: 5,
    },
    'diversion': {
        class: 'ninja',
        type: 1,
        sub: 1,
        position: { row: 4, column: 1 },
        category: 'movement',
        name: "Diversion",
        description: "Drop a smoke cloud and use the opportunity to reappear a distance away",
        iconName: "placeholder",
        damage: 0,
        time: 1000,
        cooldownTime: 15000,
        range: [0, 30],
        cost: 5,
    },
    'bladeStorm': {
        class: 'ninja',
        type: 0,
        sub: 0,
        position: { row: 3, column: 1 },
        category: 'melee',
        name: "Blade Storm",
        description: "Unleash a flurry of slashes in a surge of energy.",
        iconName: "bladeStorm",
        damage: 0,
        damageRatios: [0.13, 0, 0, 0.15],
        damageRange: [0.7, 1.3],
        effects: {
            'repeat': 0.9,
        },
        time: 100,
        cooldownTime: 10000,
        range: [5, 5],
        cost: 5,
    },
    'windSlash': {
        class: 'ninja',
        type: 0,
        sub: 0,
        position: { row: 4, column: 1 },
        category: 'ranged',
        name: "Wind Slash",
        description: "You prepare, and swing your katana so quickly that a blade of wind forms",
        iconName: "windSlash",
        damage: 0,
        damageRatios: [2, 0, 0, 2.5],
        damageRange: [0.9, 1.4],
        effects: {
            criticalChance: 0.2,
        },
        time: 4000,
        cooldownTime: 20000,
        range: [0, 50],
        cost: 5,
    },
    'drainingPalm': {
        class: 'ninja',
        type: 0,
        sub: 2,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Draining Palm",
        description: "Learning occult techniques, you use shadow powers to drain your enemies' lifeforce",
        iconName: "drainingPalm",
        damage: 0,
        damageRatios: [0, 2, 2, 0],
        damageRange: [1, 1.2],
        effects: {
            lifesteal: 0.5,
        },
        time: 3000,
        cooldownTime: 10000,
        range: [5, 5],
        cost: 5,
    },
    'katana2': {
        class: 'ninja',
        prestige:1,
        type: 0,
        sub: 0,
        position: { row: 7, column: 1 },
        category: 'melee',
        name: "Katana: Lightning Style",
        description: "You swing your blade so quickly that <br> static electricity builds on every swing",
        iconName: "katana2",
        damage: 0,
        damageRatios: [.48, 0, 0, .72],
        damageRange: [0.9, 1.1],
        effects: {
            criticalChance: 0.05,
        },
        time: 2500,
        cooldownTime: 0,
        range: [5, 5],
        cost: 1,
    },
    'hyperSpeed': {
        class: 'ninja',
        prestige:1,
        type: 3,
        sub: 0,
        position: { row: 8, column: 1 },
        category: 'buff',
        name: "Lightning Stance: First Form",
        description: "",
        iconName: "placeHolder",
        duration: 10000,
        effects: {
            actionSpeed: ["mult",3],
        },
        time: 1000,
        cooldownTime: 60000,
        range: [5, 5],
        cost: 1,
    },
    //GENERAL
    'walk': {
        type: 1,
        category: 'movement',
        name: "Move",
        description: "1. 2. 1. 2.",
        iconName: "move",
        damage: 0,
        time: 1000,
        cooldownTime: 0,
        range: [5, 0],
    },
    'wait': {
        type: 1,
        category: 'movement',
        name: "Wait",
        description: "Got nothing to do.",
        iconName: "wait",
        damage: 0,
        time: 1000,
        cooldownTime: 0,
        range: [0, 0],
    }
}