var abilityLibrary = {
    'wait': {
        type: 1,
        category: 'movement',
        name: "Wait",
        description: "Got nothing to do.",
        iconName: "wait",
        baseDamage: 0,
        time: 1000,
        cooldownTime: 0,
        range: [0, 0],
    },
    'punch': {
        type: 0,
        category: 'melee',
        name: "Punch",
        iconName: "punch",
        baseDamage: 1,
        damageRatios: [.8, 0, 0, 0.2],
        damageRange: [0.9, 1.1],
        time: 3000,
        cooldownTime: 0,
        range: [5, 5],

    },
    'smash': {
        type: 0,
        category: 'melee',
        name: "Smash",
        iconName: "smash",
        baseDamage: 5,
        damageRatios: [2.5, 1, 0, 0],
        damageRange: [0.9, 1.1],
        time: 7000,
        cooldownTime: 10000,
        range: [5, 5],

    },
    'crowbar': {
        type: 0,
        category: 'melee',
        name: "Crowbar",
        iconName: "crowbar",
        baseDamage: 1,
        damageRatios: [3, 0, 0, 0],
        damageRange: [1, 1.1],
        time: 4000,
        cooldownTime: 20000,
        range: [5, 5],
    },
    'prisonBaton': {
        type: 0,
        category: 'melee',
        name: "Baton",
        iconName: "crowbar",
        baseDamage: 0,
        damageRatios: [1.2, 0, 0, 0],
        damageRange: [1, 1.1],
        time: 3500,
        cooldownTime: 0,
        range: [5, 5],
    },
    'taser': {
        type: 0,
        category: 'melee',
        name: "Taser",
        iconName: "jab",
        baseDamage: 1,
        damageRatios: [0, 0, 0.5, 0.5],
        damageRange: [1, 1.1],
        effects: {
            'stun': 1,
        },
        time: 3000,
        cooldownTime: 20000,
        range: [5, 5],
    },
    'shank': {
        type: 0,
        category: 'melee',
        name: "Shank",
        iconName: "throwingKnife",
        baseDamage: 1,
        damageRatios: [2, 0, 0, 1],
        damageRange: [1, 1.1],
        time: 4000,
        cooldownTime: 5000,
        range: [5, 5],
    },
    'vomit': {
        type: 0,
        category: 'ranged',
        name: "Vomit",
        iconName: "vomit",
        baseDamage: 1,
        damageRatios: [0, 2.5, 0, 0],
        damageRange: [0.9, 1.1],
        time: 3000,
        cooldownTime: 7000,
        range: [0, 10],
    },
    'crabWaterJet': {
        type: 0,
        category: 'ranged',
        name: "Water Jet",
        iconName: "vomit",
        baseDamage: 0,
        damageRatios: [0, 5, 0, 0],
        damageRange: [0.9, 1.1],
        time: 5000,
        cooldownTime: 7000,
        range: [0, 50],
    },
    'mutantSlash': {
        type: 0,
        category: 'melee',
        name: "Slash",
        iconName: "mutantSlash",
        baseDamage: 1,
        damageRatios: [1.5, 1, 0, 0],
        damageRange: [1, 1.5],
        time: 4000,
        cooldownTime: 12000,
        range: [10, 10],
    },
    'regenerationExperiment': {
        type: 2,
        category: 'melee',
        name: "Regeneration",
        iconName: "secondWind",
        baseDamage: 10,
        damageRatios: [0, 0, 0, 0],
        damageRange: [1, 1],
        effects: {
            'heal': 1,
        },
        time: 2000,
        cooldownTime: 20000,
        range: [10, 10],
    },
    'handgun': {
        type: 0,
        category: 'ranged',
        name: "Handgun",
        iconName: "handgun",
        baseDamage: 1,
        damageRatios: [0, 0, 1, 1],
        damageRange: [1, 1.2],
        time: 5000,
        cooldownTime: 0,
        range: [10, 50],
    },
    'rifle': {
        type: 0,
        category: 'ranged',
        name: "Rifle",
        iconName: "handgun",
        baseDamage: 1,
        damageRatios: [0, 0, .6, .6],
        damageRange: [1, 1.2],
        time: 2500,
        cooldownTime: 0,
        range: [10, 50],
    },
    'tommy': {
        type: 0,
        category: 'ranged',
        name: "Tommy Gun",
        iconName: "handgun",
        baseDamage: 1,
        damageRatios: [.3, 0, 0, .1],
        damageRange: [0.9, 1.1],
        time: 1000,
        cooldownTime: 0,
        range: [10, 50],
    },
    'knuckleDuster': {
        type: 0,
        category: 'melee',
        name: "Knuckle Duster",
        iconName: "knuckleDuster",
        baseDamage: 1,
        damageRatios: [1.2, 0.5, 0, 0],
        damageRange: [0.9, 1.1],
        time: 4000,
        cooldownTime: 0,
        range: [5, 5],

    },
    'chokeHold': {
        type: 0,
        category: 'melee',
        name: "Chokehold",
        iconName: "placeholder",
        baseDamage: 0,
        damageRatios: [2, 0, 0, 0],
        damageRange: [0.9, 1.1],
        effects: {
            'stun': 3,
        },
        time: 5000,
        cooldownTime: 20000,
        range: [5, 5],

    },
    'gutPunch': {
        type: 0,
        category: 'melee',
        name: "Gut Punch",
        iconName: "placeholder",
        baseDamage: 1,
        damageRatios: [1.2, 0.5, 0, 0],
        damageRange: [0.9, 1.1],
        effects: {
            'stun': 3,
        },
        time: 4000,
        cooldownTime: 20000,
        range: [5, 5],

    },
    'suckerPunch': {
        type: 0,
        category: 'melee',
        name: "Sucker Punch",
        iconName: "jab",
        baseDamage: 0,
        damageRatios: [0.6, 0, 0, 0.5],
        damageRange: [0.9, 1.1],
        time: 1000,
        effects: {
            'stun': 1,
        },
        cooldownTime: 10000,
        range: [5, 5],

    },
    'telekineticProjectile': {
        type: 0,
        category: 'ranged',
        name: "Telekinetic Projectile",
        iconName: "telekineticProjectile",
        baseDamage: 0,
        damageRatios: [0, 0, 0, 2],
        damageRange: [0.9, 1.1],
        time: 3000,
        cooldownTime: 5000,
        range: [0, 60],

    },
    'confuse': {
        type: 0,
        category: 'ranged',
        name: "Confuse",
        iconName: "placeholder",
        baseDamage: 0,
        damageRatios: [0, 0, 2, 0],
        damageRange: [0.9, 1.1],
        effects: {
            'stun': 1,
        },
        time: 2000,
        cooldownTime: 12000,
        range: [0, 60],

    },
    'psychicShove': {
        type: 0,
        category: 'melee',
        name: "Psychic Shove",
        iconName: "placeholder",
        baseDamage: 0,
        damageRatios: [0, 0, 3, 0],
        damageRange: [0.9, 1.1],
        effects: {
            'knockback': 15,
        },
        time: 4000,
        cooldownTime: 14000,
        range: [10, 10],

    },
    'psionicBarrierAlly': {
        type: 2,
        category: 'ranged',
        name: "Psionic Barrier",
        iconName: "psionicBarrier",
        baseDamage: 0,
        damageRatios: [0, 0, 2, 0],
        damageRange: [0.9, 1.1],
        effects: {
            'allyshield': 1,
        },
        time: 1000,
        cooldownTime: 20000,
        range: [0, 60],

    },
    'airCannon': {
        type: 0,
        category: 'ranged',
        name: "Shockwave Punch",
        iconName: "airCannon",
        baseDamage: 0,
        damageRatios: [1, 0, 0, 0],
        damageRange: [1, 1],
        effects: {
            'knockback': 5
        },
        time: 3000,
        cooldownTime: 5000,
        range: [5, 50],
    },
    'regenerationSuperthug': {
        type: 2,
        category: 'melee',
        name: "Superhuman Recovery",
        iconName: "secondWind",
        baseDamage: 4,
        damageRatios: [0, 0, 0, 0],
        damageRange: [1, 1],
        effects: {
            'heal': 1,
        },
        time: 2000,
        cooldownTime: 10000,
        range: [10, 10],
    },
    'multipleSimplePunches': {
        type: 0,
        category: 'melee',
        name: "Multiple Simple Punches",
        iconName: "multipleSimplePunches",
        baseDamage: 0,
        damageRatios: [.3, 0, 0, .3],
        damageRange: [0.8, 1.2],
        effects: {
            'repeat': 0.5,
        },
        time: 500,
        cooldownTime: 2000,
        range: [5, 5],
        cost: 5,
    },
    'groundStomp': {
        type: 0,
        category: 'melee',
        name: "Ground Stomp",
        iconName: "placeholder",
        baseDamage: 0,
        damageRatios: [1, 1, 0, 0],
        damageRange: [1, 1],
        effects: {
            'stun': 2,
            'aoe': 10,
        },
        time: 3000,
        cooldownTime: 12000,
        range: [5, 5],
    },
    'dash': {
        type: 1,
        category: 'movement',
        name: "Dash",
        iconName: "move",
        baseDamage: 0,
        time: 500,
        cooldownTime: 5000,
        range: [5, 5],
    },
    'crabWalk': {
        type: 1,
        category: 'movement',
        name: "Crab Walk",
        iconName: "move",
        baseDamage: 0,
        time: 1000,
        cooldownTime: 5000,
        range: [10, 10],
    },
    'walk': {
        type: 1,
        category: 'movement',
        name: "Move",
        iconName: "move",
        baseDamage: 0,
        time: 1000,
        cooldownTime: 0,
        range: [5, 0],
    },

    'shove': {
        type: 0, category: 'ranged', name: "Shove", iconName: "jab",
        baseDamage: 1, damageRatios: [.2, 0, 0, 0], damageRange: [1, 1],
        time: 3000, cooldownTime: 5000, range: [5, 5],
        effects: { 'stun': 0.5, 'knockback': 10 }
    },
    'gatling': {
        type: 0, category: 'ranged', name: "Gatling", iconName: "handgun",
        baseDamage: 0, damageRatios: [.2, .1, .1, 0], damageRange: [1, 1],
        time: 1000, cooldownTime: 0, range: [10, 50],
    },
    'gatlingsalvo': {
        type: 0, category: 'ranged', name: "Gatling Salvo", iconName: "handgun",
        baseDamage: 0, damageRatios: [.3, .1, .1, 0], damageRange: [0.9, 1.1],
        time: 500, cooldownTime: 5000, range: [10, 50],
        effects: { "repeat": 0.8 }
    },
    'bladeArm': {
        type: 0, category: 'melee', name: "Blade Arm", iconName: "placeholder",
        baseDamage: 0, damageRatios: [.4, 0, 0, .4], damageRange: [0.9, 1.1],
        time: 2500, cooldownTime: 0, range: [5, 5],
        effects: { "criticalChance": 0.2 }
    },
    'bladeWhirlwind': {
        type: 0, category: 'melee', name: "Blade Whirlwind", iconName: "placeholder",
        baseDamage: 0, damageRatios: [.3, 0, 0, .1], damageRange: [0.9, 1.1],
        time: 200, cooldownTime: 5000, range: [10, 10],
        effects: { "repeat": 0.8 }
    },
    //superhuman
    'simplePunch': {
        class: 'superhuman',
        type: 0,
        sub: 0,
        position: { row: 1, column: 2 },
        category: 'melee',
        name: "Simple Punch",
        description: "I fear not the man who has practiced 10,000 punches once, but I fear the man who has practiced one punch 10,000 times.",
        iconName: "punch",
        baseDamage: 1,
        damageRatios: [1.2, 0, 0, 0.3],
        damageRange: [0.8, 1.2],
        time: 3000,
        cooldownTime: 0,
        range: [5, 5],
        cost: 0,
    },
    'multipleSimplePunches': {
        class: 'superhuman',
        type: 0,
        sub: 0,
        position: { row: 2, column: 2 },
        category: 'melee',
        name: "Multiple Simple Punches",
        description: "I fear not the man who has practiced 10,000 punches once, but I fear the man who has practiced one 10,000 punches, 10,000 times.",
        iconName: "multipleSimplePunches",
        baseDamage: 1,
        damageRatios: [.3, 0, 0, .2],
        damageRange: [0.8, 1.2],
        effects: {
            'repeat': 1,
        },
        time: 500,
        cooldownTime: 2000,
        range: [5, 5],
        cost: 0,
        requiresAbility: { 'simplePunch': 1 },

    },
    'solarPlexusStrike': {
        class: 'superhuman',
        type: 0,
        sub: 0,
        position: { row: 3, column: 5 },
        category: 'melee',
        name: "Solar Plexus Strike",
        description: "Knock the wind out of your foe with an unexpected blow",
        iconName: "solarPlexusStrike",
        baseDamage: 1,
        damageRatios: [2.5, 0, 0, 1.5],
        damageRange: [0.8, 1.2],
        effects: {
            'stun': 4,
        },
        time: 3000,
        cooldownTime: 20000,
        range: [5, 5],
        unlockPoints: 10,
        cost: 0,
    },
    'templeCrush': {
        class: 'superhuman',
        type: 0,
        sub: 0,
        position: { row: 5, column: 1 },
        category: 'melee',
        name: "Temple Breaker",
        description: "An atrocious blow that can kill out-right",
        iconName: "solarPlexusStrike",
        baseDamage: 1,
        damageRatios: [6, 0, 0, 0],
        damageRange: [1, 1.2],
        effects: {
            'overwhelm': 0.5,
        },
        time: 3000,
        cooldownTime: 30000,
        range: [5, 5],
        unlockPoints: 10,
        cost: 0,
        requiresPassive: { 'sh_0_3': 1 }
    },
    //mutant
    'bulkFist': {
        class: 'mutant',
        type: 0,
        sub: 0,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Bulk Fist",
        description: "Enlarge your fist to deliver a solid blow.",
        iconName: "bulkFist",
        baseDamage: 1,
        damageRatios: [.7, .8, 0, 0],
        damageRange: [1, 1.1],
        time: 4000,
        cooldownTime: 0,
        range: [5, 5],
        cost: 0,
    },

    'corrosiveBurst': {
        class: 'mutant',
        type: 0,
        sub: 0,
        position: { row: 2, column: 5 },
        category: 'melee',
        name: "Corrosive Burst",
        description: "Your skin explodes, covering nearby foes in acid.",
        iconName: "corrosiveBurst",
        baseDamage: 1,
        damageRatios: [0, 2, 1.5, 0],
        damageRange: [0.8, 1.2],
        effects: {
            'aoe': 10
        },
        time: 4000,
        cooldownTime: 10000,
        range: [10, 10],
        cost: 0,
    },
    'engulf': {
        class: 'mutant',
        type: 0,
        sub: 0,
        position: { row: 5, column: 1 },
        category: 'melee',
        name: "Engulf",
        description: "Try to completely subdue your target by englufing them. Deals extra damage to damaged enemies.",
        iconName: "engulf",
        baseDamage: 1,
        damageRatios: [0, 7, 0, 0],
        damageRange: [0.9, 1],
        effects: {
            'takedown': 1,
        },
        time: 6000,
        cooldownTime: 30000,
        range: [5, 5],
        cost: 0,
        requiresPassive: { 'mu_0_4': 1 }
    },
    'acidBlob': {
        class: 'mutant',
        type: 0,
        category: 'ranged',
        name: "Acid Blob",
        description: "",
        iconName: "placeholder",
        baseDamage: 0,
        damageRatios: [0, 4, 2, 0],        damageRange: [0.8, 1.2],
                effects: {
            'aoe': 10
        },
        time: 3000,        cooldownTime: 15000,        range: [0, 60],
    },
    //esper
    'immaterialStrike': {
        class: 'esper',
        type: 0,
        sub: 0,
        position: { row: 1, column: 1 },
        category: 'melee',
        name: "Immaterial Strike",
        description: "They don't even know what's hitting them.",
        iconName: "spiritFist",
        baseDamage: 0,
        damageRatios: [0, 0, 1.1, 0],
        damageRange: [0.9, 1.1],
        time: 3000,
        cooldownTime: 0,
        range: [10, 10],
        cost: 0,
    },
    'telekineticProjectile': {
        class: 'esper',
        type: 0,
        sub: 0,
        position: { row: 2, column: 1 },
        category: 'ranged',
        name: "Telekinetic Projectile",
        description: "Use your psionic powers to thrust nearby matter towards your enemy.",
        iconName: "telekineticProjectile",
        baseDamage: 0,
        damageRatios: [0, 0, 1.8, 0],
        damageRange: [0.8, 1.1],
        time: 3000,
        cooldownTime: 5000,
        range: [0, 60],
        cost: 0,
    },
    'psionicPulse': {
        class: 'esper',
        type: 0,
        sub: 0,
        position: { row: 3, column: 1 },
        category: 'melee',
        name: "Psionic Pulse",
        description: "Emit a short-range pulse that damages and knocks back nearby enemies.",
        iconName: "psionicPulse",
        baseDamage: 0,
        damageRatios: [0, .5, 1.5, 0],
        damageRange: [1, 1.2],
        effects: {
            'knockback': 10,
            'aoe': 20,
        },
        time: 3000,
        cooldownTime: 10000,
        range: [20, 20],
        cost: 0,
    },
    'psionicBarrier': {
        class: 'esper',
        type: 2,
        sub: 0,
        position: { row: 3, column: 5 },
        category: 'ranged',
        name: "Psionic Barrier",
        description: "Form a temporary barrier to block attacks.",
        iconName: "psionicBarrier",
        baseDamage: 0,
        damageRatios: [0, 0, 0.5, 0],
        damageRange: [1, 1],
        effects: {
            'shield': 0,
        },
        time: 1000,
        cooldownTime: 20000,
        range: [0, 0],
        cost: 0,
    },
    'mindMelt': {
        class: 'esper',
        type: 0,
        sub: 0,
        position: { row: 5, column: 1 },
        category: 'ranged',
        name: "Mind Melt",
        description: "Overwhelm your foe's mind with infinite thoughts.",
        iconName: "placeholder",
        baseDamage: 0,
        damageRatios: [0, 0, 10, 0],
        damageRange: [1, 1],
        time: 6000,
        cooldownTime: 30000,
        range: [0, 60],
        cost: 0,
    },
    //ninja
    'katana': {
        type: 0, category: 'melee', name: "Katana", iconName: "katana",
        baseDamage: 0, damageRatios: [.4, 0, 0, .6], damageRange: [0.9, 1.1],
        time: 2500, cooldownTime: 0, range: [5, 5]
    },
    'deflect': {
        type: 2,
        category: 'melee', name: "Deflect", iconName: "deflect",
        baseDamage: 0, damageRatios: [0.2, 0, 0, 0.1], damageRange: [1, 1], effects: {
            'shield': 0,
            'closeCombat': 1,
        },
        time: 500, cooldownTime: 5000, range: [0, 0]
    },
    'bladeStorm': {
        type: 0, category: 'melee', name: "Blade Flurry",
        iconName: "bladeStorm", baseDamage: 0, damageRatios: [0.6, 0, 0, 0.7], damageRange: [1, 1.5],
        effects: { 'repeat': 5 },
        time: 400, cooldownTime: 10000, range: [5, 5],
    },
    'windSlash': {
        type: 0, category: 'ranged', name: "Wind Slash", iconName: "windSlash",
        baseDamage: 0, damageRatios: [2, 0, 0, 2.5], damageRange: [0.9, 1.4],
        effects: {
            criticalChance: 0.2,
        },
        time: 4000, cooldownTime: 20000, range: [0, 50],
    },
};

var enemyData = {};

enemyData.criminal = {
    id: "criminal",
    name: "Purse thief",
    maxHealth: 2.5,
    attributes: [1, .5, 2, 1],
    healthRegen: 0,
    expReward: 1,
    moneyReward: 0.03,
    reputationReward: 1,
    spriteFile: "crim.png",
    portraitFile: "crimPortrait.png",
    moves: ['punch', 'walk'],
};
enemyData.thug = {
    id: "thug",
    name: "Thug",
    maxHealth: 15,
    attributes: [4, 3, 1, 2],
    healthRegen: 0,
    expReward: 5,
    moneyReward: 0.05,
    reputationReward: 1,
    spriteFile: "thug.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch', 'walk', 'crowbar'],
};

enemyData.prisoner = {
    id: "prisoner",
    name: "Prisoner",
    maxHealth: 40,
    attributes: [1, 1, .5, 1],
    healthRegen: 0,
    expReward: 20,
    moneyReward: 0.1,
    reputationReward: 1,
    spriteFile: "prisoner.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch', 'walk', 'shank'],
};
enemyData.prisoner9 = {
    id: "prisoner9",
    rank: "boss",
    name: "Prisoner 9",
    maxHealth: 120,
    attributes: [3, 3, 1, 1],
    healthRegen: 0.005,
    expReward: 40,
    moneyReward: 0.5,
    reputationReward: 1,
    spriteFile: "prisoner9.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['punch', 'smash', 'walk'],
};
enemyData.prisonguard = {
    id: "prisonguard",
    name: "Prison Guard",
    maxHealth: 100,
    attributes: [30, 50, 30, 50],
    healthRegen: 0,
    expReward: 50,
    moneyReward: 1,
    reputationReward: 1,
    spriteFile: "prisonguard.png",
    portraitFile: "thugPortrait.png",
    moves: ['taser', 'walk', 'prisonBaton'],
};
enemyData.infectedPrisoner = {
    id: "infectedPrisoner",
    name: "Strange Prisoner",
    maxHealth: 100,
    attributes: [2, 2, 1, 2],
    healthRegen: 0.005,
    expReward: 100,
    moneyReward: 1.5,
    reputationReward: 1,
    spriteFile: "infectedPrisoner.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch', 'walk', 'vomit'],
};
enemyData.experiment999 = {
    id: "experiment999",
    rank: "boss",
    name: "Experiment #999",
    maxHealth: 350,
    attributes: [2, 1, 1, 2],
    healthRegen: 0.005,
    expReward: 250,
    moneyReward: 3,
    reputationReward: 2,
    spriteFile: "experiment999.png",
    portraitFile: "thugPortrait.png",
    moves: ['walk', 'punch', 'mutantSlash', 'vomit', 'regenerationExperiment'],
};
enemyData.thug2 = {
    id: "thug2",
    name: "Hardened Thug",
    maxHealth: 300,
    attributes: [200, 200, 50, 150],
    healthRegen: 0,
    expReward: 100,
    moneyReward: 4,
    reputationReward: 1,
    spriteFile: "thug.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch', 'walk', 'crowbar'],
};
enemyData.thug3 = {
    id: "thug3",
    name: "Armed Thug",
    maxHealth: 150,
    attributes: [100, 100, 150, 200],
    healthRegen: 0,
    expReward: 100,
    moneyReward: 4,
    reputationReward: 1,
    spriteFile: "armedThug.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch', 'handgun', 'walk'],
    engagementRange: 50,
    spawnDistance: 80,
};
enemyData.thug4 = {
    id: "thug4",
    name: "Hardened Thug",
    maxHealth: 600,
    attributes: [400, 400, 100, 300],
    healthRegen: 0,
    expReward: 150,
    moneyReward: 5,
    reputationReward: 1,
    spriteFile: "thug.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch', 'crowbar', 'walk'],
};
enemyData.thug5 = {
    id: "thug5",
    name: "Rifle Thug",
    maxHealth: 300,
    attributes: [1, 1, 2, 2],
    healthRegen: 0,
    expReward: 150,
    moneyReward: 5,
    reputationReward: 1,
    spriteFile: "rifleThug.png",
    portraitFile: "thugPortrait.png",
    moves: ['punch', 'rifle', 'walk'],
    engagementRange: 50,
    spawnDistance: 80,
};
enemyData.don = {
    id: "don",
    rank: "boss",
    name: "The Don",
    maxHealth: 1000,
    attributes: [1000, 1500, 1000, 1000],
    healthRegen: 0,
    expReward: 500,
    moneyReward: 10,
    reputationReward: 3,
    spriteFile: "don.png",
    portraitFile: "thugPortrait.png",
    moves: ['tommy', 'knuckleDuster', 'walk'],
    engagementRange: 50,
    spawnDistance: 80,
};
enemyData.donbodyguard = {
    id: "donbodyguard",
    rank: "boss",
    name: "Don's Right Hand",
    maxHealth: 4000,
    attributes: [3000, 5000, 500, 2500],
    healthRegen: 0.005,
    expReward: 1250,
    moneyReward: 15,
    reputationReward: 3,
    spriteFile: "donbodyguard.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['knuckleDuster', 'smash', 'gutPunch', 'walk'],
};
enemyData.don2 = {
    id: "don2",
    rank: "boss",
    name: "The Don",
    maxHealth: 2000,
    attributes: [2400, 3000, 2000, 3000],
    healthRegen: 0,
    expReward: 1250,
    moneyReward: 15,
    reputationReward: 3,
    spriteFile: "don.png",
    portraitFile: "thugPortrait.png",
    moves: ['tommy', 'knuckleDuster', 'walk'],
    engagementRange: 50,
    spawnDistance: 80,
};
enemyData.infusedthug = {
    id: "infusedthug",
    name: "Infused Thug",
    maxHealth: 4000,
    attributes: [6000, 5000, 2000, 4000],
    healthRegen: 0,
    expReward: 1500,
    moneyReward: 50,
    reputationReward: 2,
    spriteFile: "donbodyguard.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['knuckleDuster', 'smash', 'suckerPunch', 'walk', 'dash'],
};
enemyData.psychicthug = {
    id: "psychicthug",
    name: "Psychic Thug",
    maxHealth: 2000,
    attributes: [1000, 3000, 8000, 3000],
    healthRegen: 0,
    expReward: 1500,
    moneyReward: 50,
    reputationReward: 2,
    spriteFile: "psychicthug.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['punch', 'psionicBarrierAlly', 'telekineticProjectile', 'psychicShove', 'confuse', 'walk'],
    engagementRange: 60,
    spawnDistance: 80,
};
enemyData.superthug = {
    id: "superthug",
    rank: "boss",
    name: "Superthug",
    maxHealth: 11000,
    attributes: [25000, 20000, 4000, 20000],
    healthRegen: 0,
    expReward: 3000,
    moneyReward: 75,
    reputationReward: 6,
    spriteFile: "superthug.png",
    portraitFile: "thug.png",
    moves: ['walk', 'dash', 'punch', 'groundStomp', 'multipleSimplePunches', 'airCannon', 'regenerationSuperthug'],
};
enemyData.gatlingthug = {
    id: "gatlingthug",
    name: "Gatling Thug",
    maxHealth: 10000,
    attributes: [60000, 60000, 40000, 10000],
    healthRegen: 0,
    expReward: 7000,
    moneyReward: 100,
    reputationReward: 2,
    spriteFile: "gatlingthug.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['gatling', 'gatlingsalvo', 'shove', 'walk'],
    engagementRange: 50,
    spawnDistance: 80,
};
enemyData.morphedthug = {
    id: "morphedthug",
    name: "Morphed Thug",
    maxHealth: 12000,
    attributes: [90000, 60000, 10000, 40000],
    healthRegen: 0,
    expReward: 7000,
    moneyReward: 100,
    reputationReward: 2,
    spriteFile: "morphedthug.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['bladeArm', 'bladeWhirlwind', 'shove', 'walk'],
    spawnDistance: 50,
};
enemyData.crabman = {
    id: "crabman",
    rank: "boss",
    name: "The Crabman",
    maxHealth: 70000,
    attributes: [2.5, 3, 0.5, 1],
    healthRegen: 0.01,
    expReward: 32000,
    moneyReward: 200,
    reputationReward: 10,
    spriteFile: "crabman.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['walk', 'crabWalk', 'punch', 'smash', 'groundStomp', 'mutantSlash', 'crabWaterJet'],
};
enemyData.ultracrabman = {
    id: "ultracrabman",
    rank: "boss",
    name: "The Ultra Crabman",
    maxHealth: 250000,
    attributes: [2.5, 3, 0.5, 1],
    healthRegen: 0.01,
    expReward: 250000,
    moneyReward: 300,
    reputationReward: 40,
    spriteFile: "crabman.png",
    portraitFile: "prisoner9Portrait.png",
    moves: ['walk', 'crabWalk', 'punch', 'smash', 'groundStomp', 'mutantSlash', 'crabWaterJet'],
};
enemyData.rogueNinja = {
    id: "rogueNinja",
    rank: "boss",
    name: "Rogue Ninja",
    attributes: [2, 1, 1, 2.5],
    healthRegen: 0,
    reputationReward: 40,
    spriteFile: "ninjaSprite1.png",
    moves: ['walk', 'deflect', 'windSlash', 'bladeStorm', 'katana'],
};
enemyData.rogueEsper = {
    id: "rogueEsper",
    rank: "boss",
    name: "Rogue Esper",
    attributes: [1, 1, 3, 1.5],
    healthRegen: 0,
    reputationReward: 40,
    spriteFile: "esperSprite1.png",
    moves: ['walk', 'telekineticProjectile', 'mindMelt', 'psionicPulse', 'psionicBarrier'],
};
enemyData.rogueMutant = {
    id: "rogueMutant",
    rank: "boss",
    name: "Rogue Mutant",
    attributes: [1, 2.5, 1.5, 1],
    healthRegen: 0.01,
    reputationReward: 40,
    spriteFile: "mutantSprite1.png",
    moves: ['walk', 'bulkFist', 'corrosiveBurst', 'engulf', 'acidBlob'],
};
enemyData.rogueSuperhuman = {
    id: "rogueSuperhuman",
    rank: "boss",
    name: "Rogue Superhuman",
    attributes: [2, 1, 1, 2],
    healthRegen: 0,
    reputationReward: 40,
    spriteFile: "superhumanSprite1.png",
    moves: ['walk','dash', 'simplePunch', 'multipleSimplePunches', 'solarPlexusStrike', 'templeCrush'],
};
